export type GalleryCategory =
  | "all"
  | "bricklaying"
  | "extensions"
  | "paving"
  | "structural"
  | "repointing";

export interface GalleryImage {
  id: string;
  src: string;
  alt: string;
  category: Exclude<GalleryCategory, "all">;
  projectSlug: string;
  projectTitle: string;
}

export const galleryCategories: { value: GalleryCategory; label: string }[] = [
  { value: "all", label: "All Projects" },
  { value: "bricklaying", label: "Bricklaying" },
  { value: "extensions", label: "Extensions" },
  { value: "paving", label: "Paving" },
  { value: "structural", label: "Structural" },
  { value: "repointing", label: "Repointing" },
];

export const galleryCategoryDetails: Record<
  Exclude<GalleryCategory, "all">,
  { label: string; summary: string }
> = {
  bricklaying: {
    label: "Bricklaying",
    summary:
      "Garden walls, boundary walls, decorative brickwork and blockwork across Conwy and North Wales.",
  },
  extensions: {
    label: "Extensions",
    summary:
      "Home extensions, garages, foundations and new build projects in Conwy, Deganwy and surrounding areas.",
  },
  paving: {
    label: "Paving",
    summary:
      "Patios, sandstone paving, garden transformations and outdoor landscaping across North Wales.",
  },
  structural: {
    label: "Structural",
    summary:
      "Wall removals, lintels, concrete bases, fencing and structural alterations by local builders.",
  },
  repointing: {
    label: "Repointing",
    summary:
      "Chimney repointing, brick repairs and restoration work on period and modern properties.",
  },
};

export const galleryImages: GalleryImage[] = [
  {
    id: "coastal-block-extension-deganwy-01",
    src: "/images/projects/coastal-block-extension-deganwy/coastal-block-extension-deganwy-overview-01.jpg",
    alt: "Coastal home extension blockwork by Cimatti & Roberts in Deganwy, North Wales — overview view",
    category: "extensions",
    projectSlug: "coastal-block-extension-deganwy",
    projectTitle: "Coastal Block Extension — Deganwy",
  },
  {
    id: "coastal-block-extension-deganwy-02",
    src: "/images/projects/coastal-block-extension-deganwy/coastal-block-extension-deganwy-detail-02.jpg",
    alt: "Coastal home extension blockwork by Cimatti & Roberts in Deganwy, North Wales — detail view",
    category: "extensions",
    projectSlug: "coastal-block-extension-deganwy",
    projectTitle: "Coastal Block Extension — Deganwy",
  },
  {
    id: "extension-entrance-steps-conwy-01",
    src: "/images/projects/extension-entrance-steps-conwy/extension-entrance-steps-conwy-overview-01.jpg",
    alt: "Brick and stone entrance steps to a new home extension by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "extensions",
    projectSlug: "extension-entrance-steps-conwy",
    projectTitle: "Extension Entrance Steps — Conwy",
  },
  {
    id: "extension-entrance-steps-conwy-02",
    src: "/images/projects/extension-entrance-steps-conwy/extension-entrance-steps-conwy-detail-02.jpg",
    alt: "Brick and stone entrance steps to a new home extension by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "extensions",
    projectSlug: "extension-entrance-steps-conwy",
    projectTitle: "Extension Entrance Steps — Conwy",
  },
  {
    id: "garden-wall-brick-pillars-conwy-01",
    src: "/images/projects/garden-wall-brick-pillars-conwy/garden-wall-brick-pillars-conwy-overview-01.jpg",
    alt: "Multi-toned brick garden wall and pillars by Cimatti & Roberts in Conwy — overview view",
    category: "bricklaying",
    projectSlug: "garden-wall-brick-pillars-conwy",
    projectTitle: "Garden Wall & Pillars — Conwy",
  },
  {
    id: "decorative-brick-facing-wall-01",
    src: "/images/projects/decorative-brick-facing-wall/decorative-brick-facing-wall-overview-01.jpg",
    alt: "Red brick facing over concrete block wall by Cimatti & Roberts in North Wales — overview view",
    category: "bricklaying",
    projectSlug: "decorative-brick-facing-wall",
    projectTitle: "Decorative Brick Facing — North Wales",
  },
  {
    id: "garden-wall-hedge-north-wales-01",
    src: "/images/projects/garden-wall-hedge-north-wales/garden-wall-hedge-north-wales-overview-01.jpg",
    alt: "New multi-toned brick garden wall by Cimatti & Roberts in North Wales — overview view",
    category: "bricklaying",
    projectSlug: "garden-wall-hedge-north-wales",
    projectTitle: "Garden Wall Construction — North Wales",
  },
  {
    id: "timber-partition-bedroom-conwy-01",
    src: "/images/projects/timber-partition-bedroom-conwy/timber-partition-bedroom-conwy-overview-01.jpg",
    alt: "Custom timber partition wall by Cimatti & Roberts in a Conwy home — overview view",
    category: "structural",
    projectSlug: "timber-partition-bedroom-conwy",
    projectTitle: "Timber Partition Wall — Conwy",
  },
  {
    id: "interior-floor-screeding-conwy-01",
    src: "/images/projects/interior-floor-screeding-conwy/interior-floor-screeding-conwy-overview-01.jpg",
    alt: "Self-levelling floor screed during home extension by Cimatti & Roberts in Conwy — overview view",
    category: "extensions",
    projectSlug: "interior-floor-screeding-conwy",
    projectTitle: "Interior Floor Screeding — Conwy",
  },
  {
    id: "timber-partition-bedroom-conwy-02",
    src: "/images/projects/timber-partition-bedroom-conwy/timber-partition-bedroom-conwy-detail-02.jpg",
    alt: "Custom timber partition wall by Cimatti & Roberts in a Conwy home — detail view",
    category: "structural",
    projectSlug: "timber-partition-bedroom-conwy",
    projectTitle: "Timber Partition Wall — Conwy",
  },
  {
    id: "timber-partition-bedroom-conwy-03",
    src: "/images/projects/timber-partition-bedroom-conwy/timber-partition-bedroom-conwy-progress-03.jpg",
    alt: "Custom timber partition wall by Cimatti & Roberts in a Conwy home — progress view",
    category: "structural",
    projectSlug: "timber-partition-bedroom-conwy",
    projectTitle: "Timber Partition Wall — Conwy",
  },
  {
    id: "interior-plastering-stud-walls-01",
    src: "/images/projects/interior-plastering-stud-walls/interior-plastering-stud-walls-overview-01.jpg",
    alt: "Fresh plaster ceiling and stud wall framing by Cimatti & Roberts in North Wales — overview view",
    category: "extensions",
    projectSlug: "interior-plastering-stud-walls",
    projectTitle: "Interior Plastering & Stud Walls — North Wales",
  },
  {
    id: "blockwork-foundation-north-wales-01",
    src: "/images/projects/blockwork-foundation-north-wales/blockwork-foundation-north-wales-overview-01.jpg",
    alt: "Concrete block foundation walls by Cimatti & Roberts in rural North Wales — overview view",
    category: "extensions",
    projectSlug: "blockwork-foundation-north-wales",
    projectTitle: "Blockwork Foundation — North Wales",
  },
  {
    id: "rear-home-extension-conwy-01",
    src: "/images/projects/rear-home-extension-conwy/rear-home-extension-conwy-overview-01.jpg",
    alt: "Rear brick home extension by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "extensions",
    projectSlug: "rear-home-extension-conwy",
    projectTitle: "Rear Home Extension — Conwy",
  },
  {
    id: "house-extension-insulation-conwy-01",
    src: "/images/projects/house-extension-insulation-conwy/house-extension-insulation-conwy-overview-01.jpg",
    alt: "Blockwork home extension with insulation boards by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "extensions",
    projectSlug: "house-extension-insulation-conwy",
    projectTitle: "House Extension with Insulation — Conwy",
  },
  {
    id: "house-extension-insulation-conwy-02",
    src: "/images/projects/house-extension-insulation-conwy/house-extension-insulation-conwy-detail-02.jpg",
    alt: "Blockwork home extension with insulation boards by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "extensions",
    projectSlug: "house-extension-insulation-conwy",
    projectTitle: "House Extension with Insulation — Conwy",
  },
  {
    id: "blockwork-foundation-north-wales-02",
    src: "/images/projects/blockwork-foundation-north-wales/blockwork-foundation-north-wales-detail-02.jpg",
    alt: "Concrete block foundation walls by Cimatti & Roberts in rural North Wales — detail view",
    category: "extensions",
    projectSlug: "blockwork-foundation-north-wales",
    projectTitle: "Blockwork Foundation — North Wales",
  },
  {
    id: "blockwork-foundation-north-wales-03",
    src: "/images/projects/blockwork-foundation-north-wales/blockwork-foundation-north-wales-progress-03.jpg",
    alt: "Concrete block foundation walls by Cimatti & Roberts in rural North Wales — progress view",
    category: "extensions",
    projectSlug: "blockwork-foundation-north-wales",
    projectTitle: "Blockwork Foundation — North Wales",
  },
  {
    id: "flagstone-steps-brick-risers-01",
    src: "/images/projects/flagstone-steps-brick-risers/flagstone-steps-brick-risers-overview-01.jpg",
    alt: "Flagstone steps with red brick risers by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "paving",
    projectSlug: "flagstone-steps-brick-risers",
    projectTitle: "Flagstone Steps with Brick Risers — Conwy",
  },
  {
    id: "flagstone-steps-brick-risers-02",
    src: "/images/projects/flagstone-steps-brick-risers/flagstone-steps-brick-risers-detail-02.jpg",
    alt: "Flagstone steps with red brick risers by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "paving",
    projectSlug: "flagstone-steps-brick-risers",
    projectTitle: "Flagstone Steps with Brick Risers — Conwy",
  },
  {
    id: "stone-patio-rendered-planter-conwy-01",
    src: "/images/projects/stone-patio-rendered-planter-conwy/stone-patio-rendered-planter-conwy-overview-01.jpg",
    alt: "Natural stone patio and rendered raised planter by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "paving",
    projectSlug: "stone-patio-rendered-planter-conwy",
    projectTitle: "Stone Patio & Rendered Planter — Conwy",
  },
  {
    id: "stone-patio-rendered-planter-conwy-02",
    src: "/images/projects/stone-patio-rendered-planter-conwy/stone-patio-rendered-planter-conwy-detail-02.jpg",
    alt: "Natural stone patio and rendered raised planter by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "paving",
    projectSlug: "stone-patio-rendered-planter-conwy",
    projectTitle: "Stone Patio & Rendered Planter — Conwy",
  },
  {
    id: "boundary-wall-coping-conwy-01",
    src: "/images/projects/boundary-wall-coping-conwy/boundary-wall-coping-conwy-overview-01.jpg",
    alt: "Boundary wall with stone coping by Cimatti & Roberts in Conwy — overview view",
    category: "bricklaying",
    projectSlug: "boundary-wall-coping-conwy",
    projectTitle: "Boundary Wall with Coping — Conwy",
  },
  {
    id: "stone-steps-rendered-north-wales-01",
    src: "/images/projects/stone-steps-rendered-north-wales/stone-steps-rendered-north-wales-overview-01.jpg",
    alt: "Natural stone steps with rendered risers by Cimatti & Roberts in North Wales — overview view",
    category: "paving",
    projectSlug: "stone-steps-rendered-north-wales",
    projectTitle: "Stone Steps with Rendered Risers — North Wales",
  },
  {
    id: "stone-steps-rendered-north-wales-02",
    src: "/images/projects/stone-steps-rendered-north-wales/stone-steps-rendered-north-wales-detail-02.jpg",
    alt: "Natural stone steps with rendered risers by Cimatti & Roberts in North Wales — detail view",
    category: "paving",
    projectSlug: "stone-steps-rendered-north-wales",
    projectTitle: "Stone Steps with Rendered Risers — North Wales",
  },
  {
    id: "stone-steps-rendered-north-wales-03",
    src: "/images/projects/stone-steps-rendered-north-wales/stone-steps-rendered-north-wales-progress-03.jpg",
    alt: "Natural stone steps with rendered risers by Cimatti & Roberts in North Wales — progress view",
    category: "paving",
    projectSlug: "stone-steps-rendered-north-wales",
    projectTitle: "Stone Steps with Rendered Risers — North Wales",
  },
  {
    id: "decorative-brick-screen-wall-conwy-01",
    src: "/images/projects/decorative-brick-screen-wall-conwy/decorative-brick-screen-wall-conwy-overview-01.jpg",
    alt: "Red brick garden wall with decorative screen blocks by Cimatti & Roberts in Conwy — overview view",
    category: "bricklaying",
    projectSlug: "decorative-brick-screen-wall-conwy",
    projectTitle: "Decorative Brick Screen Wall — Conwy",
  },
  {
    id: "grey-sandstone-patio-conwy-01",
    src: "/images/projects/grey-sandstone-patio-conwy/grey-sandstone-patio-conwy-overview-01.jpg",
    alt: "Grey natural stone patio slabs by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "paving",
    projectSlug: "grey-sandstone-patio-conwy",
    projectTitle: "Grey Sandstone Patio — Conwy",
  },
  {
    id: "concrete-base-slab-north-wales-01",
    src: "/images/projects/concrete-base-slab-north-wales/concrete-base-slab-north-wales-overview-01.jpg",
    alt: "Freshly poured concrete base slab by Cimatti & Roberts in North Wales — overview view",
    category: "structural",
    projectSlug: "concrete-base-slab-north-wales",
    projectTitle: "Concrete Base Slab — North Wales",
  },
  {
    id: "decorative-brick-screen-wall-conwy-02",
    src: "/images/projects/decorative-brick-screen-wall-conwy/decorative-brick-screen-wall-conwy-detail-02.jpg",
    alt: "Red brick garden wall with decorative screen blocks by Cimatti & Roberts in Conwy — detail view",
    category: "bricklaying",
    projectSlug: "decorative-brick-screen-wall-conwy",
    projectTitle: "Decorative Brick Screen Wall — Conwy",
  },
  {
    id: "decorative-brick-screen-wall-conwy-03",
    src: "/images/projects/decorative-brick-screen-wall-conwy/decorative-brick-screen-wall-conwy-progress-03.jpg",
    alt: "Red brick garden wall with decorative screen blocks by Cimatti & Roberts in Conwy — progress view",
    category: "bricklaying",
    projectSlug: "decorative-brick-screen-wall-conwy",
    projectTitle: "Decorative Brick Screen Wall — Conwy",
  },
  {
    id: "concrete-base-slab-north-wales-02",
    src: "/images/projects/concrete-base-slab-north-wales/concrete-base-slab-north-wales-detail-02.jpg",
    alt: "Freshly poured concrete base slab by Cimatti & Roberts in North Wales — detail view",
    category: "structural",
    projectSlug: "concrete-base-slab-north-wales",
    projectTitle: "Concrete Base Slab — North Wales",
  },
  {
    id: "decorative-brick-screen-wall-conwy-04",
    src: "/images/projects/decorative-brick-screen-wall-conwy/decorative-brick-screen-wall-conwy-exterior-04.jpg",
    alt: "Red brick garden wall with decorative screen blocks by Cimatti & Roberts in Conwy — exterior view",
    category: "bricklaying",
    projectSlug: "decorative-brick-screen-wall-conwy",
    projectTitle: "Decorative Brick Screen Wall — Conwy",
  },
  {
    id: "grey-sandstone-patio-conwy-02",
    src: "/images/projects/grey-sandstone-patio-conwy/grey-sandstone-patio-conwy-detail-02.jpg",
    alt: "Grey natural stone patio slabs by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "paving",
    projectSlug: "grey-sandstone-patio-conwy",
    projectTitle: "Grey Sandstone Patio — Conwy",
  },
  {
    id: "garden-transformation-conwy-01",
    src: "/images/projects/garden-transformation-conwy/garden-transformation-conwy-overview-01.jpg",
    alt: "Sandstone patio and timber gazebo garden transformation by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "paving",
    projectSlug: "garden-transformation-conwy",
    projectTitle: "Garden Transformation — Conwy",
  },
  {
    id: "industrial-blockwork-wall-01",
    src: "/images/projects/industrial-blockwork-wall/industrial-blockwork-wall-overview-01.jpg",
    alt: "Internal concrete block wall construction by Cimatti & Roberts in North Wales — overview view",
    category: "bricklaying",
    projectSlug: "industrial-blockwork-wall",
    projectTitle: "Industrial Blockwork Wall — North Wales",
  },
  {
    id: "decorative-brick-screen-wall-conwy-05",
    src: "/images/projects/decorative-brick-screen-wall-conwy/decorative-brick-screen-wall-conwy-interior-05.jpg",
    alt: "Red brick garden wall with decorative screen blocks by Cimatti & Roberts in Conwy — interior view",
    category: "bricklaying",
    projectSlug: "decorative-brick-screen-wall-conwy",
    projectTitle: "Decorative Brick Screen Wall — Conwy",
  },
  {
    id: "industrial-blockwork-wall-02",
    src: "/images/projects/industrial-blockwork-wall/industrial-blockwork-wall-detail-02.jpg",
    alt: "Internal concrete block wall construction by Cimatti & Roberts in North Wales — detail view",
    category: "bricklaying",
    projectSlug: "industrial-blockwork-wall",
    projectTitle: "Industrial Blockwork Wall — North Wales",
  },
  {
    id: "industrial-blockwork-wall-03",
    src: "/images/projects/industrial-blockwork-wall/industrial-blockwork-wall-progress-03.jpg",
    alt: "Internal concrete block wall construction by Cimatti & Roberts in North Wales — progress view",
    category: "bricklaying",
    projectSlug: "industrial-blockwork-wall",
    projectTitle: "Industrial Blockwork Wall — North Wales",
  },
  {
    id: "industrial-blockwork-wall-04",
    src: "/images/projects/industrial-blockwork-wall/industrial-blockwork-wall-exterior-04.jpg",
    alt: "Internal concrete block wall construction by Cimatti & Roberts in North Wales — exterior view",
    category: "bricklaying",
    projectSlug: "industrial-blockwork-wall",
    projectTitle: "Industrial Blockwork Wall — North Wales",
  },
  {
    id: "commercial-brick-wall-north-wales-01",
    src: "/images/projects/commercial-brick-wall-north-wales/commercial-brick-wall-north-wales-overview-01.jpg",
    alt: "Large-scale commercial brick wall by Cimatti & Roberts in North Wales — overview view",
    category: "bricklaying",
    projectSlug: "commercial-brick-wall-north-wales",
    projectTitle: "Commercial Brick Wall — North Wales",
  },
  {
    id: "blockwork-garden-wall-conwy-01",
    src: "/images/projects/blockwork-garden-wall-conwy/blockwork-garden-wall-conwy-overview-01.jpg",
    alt: "Grey blockwork garden wall with brick coping by Cimatti & Roberts in Conwy — overview view",
    category: "bricklaying",
    projectSlug: "blockwork-garden-wall-conwy",
    projectTitle: "Blockwork Garden Wall — Conwy",
  },
  {
    id: "blockwork-garden-wall-conwy-02",
    src: "/images/projects/blockwork-garden-wall-conwy/blockwork-garden-wall-conwy-detail-02.jpg",
    alt: "Grey blockwork garden wall with brick coping by Cimatti & Roberts in Conwy — detail view",
    category: "bricklaying",
    projectSlug: "blockwork-garden-wall-conwy",
    projectTitle: "Blockwork Garden Wall — Conwy",
  },
  {
    id: "blockwork-garden-wall-conwy-03",
    src: "/images/projects/blockwork-garden-wall-conwy/blockwork-garden-wall-conwy-progress-03.jpg",
    alt: "Grey blockwork garden wall with brick coping by Cimatti & Roberts in Conwy — progress view",
    category: "bricklaying",
    projectSlug: "blockwork-garden-wall-conwy",
    projectTitle: "Blockwork Garden Wall — Conwy",
  },
  {
    id: "blockwork-garden-wall-conwy-04",
    src: "/images/projects/blockwork-garden-wall-conwy/blockwork-garden-wall-conwy-exterior-04.jpg",
    alt: "Grey blockwork garden wall with brick coping by Cimatti & Roberts in Conwy — exterior view",
    category: "bricklaying",
    projectSlug: "blockwork-garden-wall-conwy",
    projectTitle: "Blockwork Garden Wall — Conwy",
  },
  {
    id: "blockwork-garden-wall-conwy-05",
    src: "/images/projects/blockwork-garden-wall-conwy/blockwork-garden-wall-conwy-interior-05.jpg",
    alt: "Grey blockwork garden wall with brick coping by Cimatti & Roberts in Conwy — interior view",
    category: "bricklaying",
    projectSlug: "blockwork-garden-wall-conwy",
    projectTitle: "Blockwork Garden Wall — Conwy",
  },
  {
    id: "stone-chimney-repointing-north-wales-01",
    src: "/images/projects/stone-chimney-repointing-north-wales/stone-chimney-repointing-north-wales-overview-01.jpg",
    alt: "Stone chimney stack repointing by Cimatti & Roberts in North Wales — overview view",
    category: "repointing",
    projectSlug: "stone-chimney-repointing-north-wales",
    projectTitle: "Stone Chimney Repointing — North Wales",
  },
  {
    id: "blockwork-garden-wall-conwy-06",
    src: "/images/projects/blockwork-garden-wall-conwy/blockwork-garden-wall-conwy-foundation-06.jpg",
    alt: "Grey blockwork garden wall with brick coping by Cimatti & Roberts in Conwy — foundation view",
    category: "bricklaying",
    projectSlug: "blockwork-garden-wall-conwy",
    projectTitle: "Blockwork Garden Wall — Conwy",
  },
  {
    id: "stone-chimney-repointing-north-wales-02",
    src: "/images/projects/stone-chimney-repointing-north-wales/stone-chimney-repointing-north-wales-detail-02.jpg",
    alt: "Stone chimney stack repointing by Cimatti & Roberts in North Wales — detail view",
    category: "repointing",
    projectSlug: "stone-chimney-repointing-north-wales",
    projectTitle: "Stone Chimney Repointing — North Wales",
  },
  {
    id: "blockwork-garden-wall-conwy-07",
    src: "/images/projects/blockwork-garden-wall-conwy/blockwork-garden-wall-conwy-blockwork-07.jpg",
    alt: "Grey blockwork garden wall with brick coping by Cimatti & Roberts in Conwy — blockwork view",
    category: "bricklaying",
    projectSlug: "blockwork-garden-wall-conwy",
    projectTitle: "Blockwork Garden Wall — Conwy",
  },
  {
    id: "stone-chimney-repointing-north-wales-03",
    src: "/images/projects/stone-chimney-repointing-north-wales/stone-chimney-repointing-north-wales-progress-03.jpg",
    alt: "Stone chimney stack repointing by Cimatti & Roberts in North Wales — progress view",
    category: "repointing",
    projectSlug: "stone-chimney-repointing-north-wales",
    projectTitle: "Stone Chimney Repointing — North Wales",
  },
  {
    id: "stone-chimney-repointing-north-wales-04",
    src: "/images/projects/stone-chimney-repointing-north-wales/stone-chimney-repointing-north-wales-exterior-04.jpg",
    alt: "Stone chimney stack repointing by Cimatti & Roberts in North Wales — exterior view",
    category: "repointing",
    projectSlug: "stone-chimney-repointing-north-wales",
    projectTitle: "Stone Chimney Repointing — North Wales",
  },
  {
    id: "stone-chimney-repointing-north-wales-05",
    src: "/images/projects/stone-chimney-repointing-north-wales/stone-chimney-repointing-north-wales-interior-05.jpg",
    alt: "Stone chimney stack repointing by Cimatti & Roberts in North Wales — interior view",
    category: "repointing",
    projectSlug: "stone-chimney-repointing-north-wales",
    projectTitle: "Stone Chimney Repointing — North Wales",
  },
  {
    id: "circular-stone-patio-conwy-01",
    src: "/images/projects/circular-stone-patio-conwy/circular-stone-patio-conwy-overview-01.jpg",
    alt: "Decorative circular stone patio by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "paving",
    projectSlug: "circular-stone-patio-conwy",
    projectTitle: "Circular Stone Patio — Conwy",
  },
  {
    id: "circular-stone-patio-conwy-02",
    src: "/images/projects/circular-stone-patio-conwy/circular-stone-patio-conwy-detail-02.jpg",
    alt: "Decorative circular stone patio by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "paving",
    projectSlug: "circular-stone-patio-conwy",
    projectTitle: "Circular Stone Patio — Conwy",
  },
  {
    id: "circular-stone-patio-conwy-03",
    src: "/images/projects/circular-stone-patio-conwy/circular-stone-patio-conwy-progress-03.jpg",
    alt: "Decorative circular stone patio by Cimatti & Roberts in Conwy, North Wales — progress view",
    category: "paving",
    projectSlug: "circular-stone-patio-conwy",
    projectTitle: "Circular Stone Patio — Conwy",
  },
  {
    id: "circular-stone-patio-conwy-04",
    src: "/images/projects/circular-stone-patio-conwy/circular-stone-patio-conwy-exterior-04.jpg",
    alt: "Decorative circular stone patio by Cimatti & Roberts in Conwy, North Wales — exterior view",
    category: "paving",
    projectSlug: "circular-stone-patio-conwy",
    projectTitle: "Circular Stone Patio — Conwy",
  },
  {
    id: "circular-stone-patio-conwy-05",
    src: "/images/projects/circular-stone-patio-conwy/circular-stone-patio-conwy-interior-05.jpg",
    alt: "Decorative circular stone patio by Cimatti & Roberts in Conwy, North Wales — interior view",
    category: "paving",
    projectSlug: "circular-stone-patio-conwy",
    projectTitle: "Circular Stone Patio — Conwy",
  },
  {
    id: "circular-stone-patio-conwy-06",
    src: "/images/projects/circular-stone-patio-conwy/circular-stone-patio-conwy-foundation-06.jpg",
    alt: "Decorative circular stone patio by Cimatti & Roberts in Conwy, North Wales — foundation view",
    category: "paving",
    projectSlug: "circular-stone-patio-conwy",
    projectTitle: "Circular Stone Patio — Conwy",
  },
  {
    id: "block-wall-stone-foundation-conwy-01",
    src: "/images/projects/block-wall-stone-foundation-conwy/block-wall-stone-foundation-conwy-overview-01.jpg",
    alt: "Concrete block wall on stone foundation by Cimatti & Roberts in Conwy — overview view",
    category: "bricklaying",
    projectSlug: "block-wall-stone-foundation-conwy",
    projectTitle: "Block Wall on Stone Foundation — Conwy",
  },
  {
    id: "block-wall-stone-foundation-conwy-02",
    src: "/images/projects/block-wall-stone-foundation-conwy/block-wall-stone-foundation-conwy-detail-02.jpg",
    alt: "Concrete block wall on stone foundation by Cimatti & Roberts in Conwy — detail view",
    category: "bricklaying",
    projectSlug: "block-wall-stone-foundation-conwy",
    projectTitle: "Block Wall on Stone Foundation — Conwy",
  },
  {
    id: "block-wall-stone-foundation-conwy-03",
    src: "/images/projects/block-wall-stone-foundation-conwy/block-wall-stone-foundation-conwy-progress-03.jpg",
    alt: "Concrete block wall on stone foundation by Cimatti & Roberts in Conwy — progress view",
    category: "bricklaying",
    projectSlug: "block-wall-stone-foundation-conwy",
    projectTitle: "Block Wall on Stone Foundation — Conwy",
  },
  {
    id: "side-extension-blockwork-conwy-01",
    src: "/images/projects/side-extension-blockwork-conwy/side-extension-blockwork-conwy-overview-01.jpg",
    alt: "Single-storey blockwork extension by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "extensions",
    projectSlug: "side-extension-blockwork-conwy",
    projectTitle: "Side Extension Blockwork — Conwy",
  },
  {
    id: "side-extension-blockwork-conwy-02",
    src: "/images/projects/side-extension-blockwork-conwy/side-extension-blockwork-conwy-detail-02.jpg",
    alt: "Single-storey blockwork extension by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "extensions",
    projectSlug: "side-extension-blockwork-conwy",
    projectTitle: "Side Extension Blockwork — Conwy",
  },
  {
    id: "natural-stone-patio-terrace-conwy-01",
    src: "/images/projects/natural-stone-patio-terrace-conwy/natural-stone-patio-terrace-conwy-overview-01.jpg",
    alt: "Natural stone patio with masonry walling by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "paving",
    projectSlug: "natural-stone-patio-terrace-conwy",
    projectTitle: "Natural Stone Patio — Conwy Terrace",
  },
  {
    id: "courtyard-sandstone-patio-conwy-01",
    src: "/images/projects/courtyard-sandstone-patio-conwy/courtyard-sandstone-patio-conwy-overview-01.jpg",
    alt: "Multi-toned sandstone courtyard patio by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "paving",
    projectSlug: "courtyard-sandstone-patio-conwy",
    projectTitle: "Courtyard Sandstone Patio — Conwy",
  },
  {
    id: "natural-stone-patio-terrace-conwy-02",
    src: "/images/projects/natural-stone-patio-terrace-conwy/natural-stone-patio-terrace-conwy-detail-02.jpg",
    alt: "Natural stone patio with masonry walling by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "paving",
    projectSlug: "natural-stone-patio-terrace-conwy",
    projectTitle: "Natural Stone Patio — Conwy Terrace",
  },
  {
    id: "courtyard-sandstone-patio-conwy-02",
    src: "/images/projects/courtyard-sandstone-patio-conwy/courtyard-sandstone-patio-conwy-detail-02.jpg",
    alt: "Multi-toned sandstone courtyard patio by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "paving",
    projectSlug: "courtyard-sandstone-patio-conwy",
    projectTitle: "Courtyard Sandstone Patio — Conwy",
  },
  {
    id: "courtyard-sandstone-patio-conwy-03",
    src: "/images/projects/courtyard-sandstone-patio-conwy/courtyard-sandstone-patio-conwy-progress-03.jpg",
    alt: "Multi-toned sandstone courtyard patio by Cimatti & Roberts in Conwy, North Wales — progress view",
    category: "paving",
    projectSlug: "courtyard-sandstone-patio-conwy",
    projectTitle: "Courtyard Sandstone Patio — Conwy",
  },
  {
    id: "courtyard-sandstone-patio-conwy-04",
    src: "/images/projects/courtyard-sandstone-patio-conwy/courtyard-sandstone-patio-conwy-exterior-04.jpg",
    alt: "Multi-toned sandstone courtyard patio by Cimatti & Roberts in Conwy, North Wales — exterior view",
    category: "paving",
    projectSlug: "courtyard-sandstone-patio-conwy",
    projectTitle: "Courtyard Sandstone Patio — Conwy",
  },
  {
    id: "indian-sandstone-patio-conwy-01",
    src: "/images/projects/indian-sandstone-patio-conwy/indian-sandstone-patio-conwy-overview-01.jpg",
    alt: "Indian sandstone patio with circular feature by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "paving",
    projectSlug: "indian-sandstone-patio-conwy",
    projectTitle: "Indian Sandstone Patio — Conwy",
  },
  {
    id: "indian-sandstone-patio-conwy-02",
    src: "/images/projects/indian-sandstone-patio-conwy/indian-sandstone-patio-conwy-detail-02.jpg",
    alt: "Indian sandstone patio with circular feature by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "paving",
    projectSlug: "indian-sandstone-patio-conwy",
    projectTitle: "Indian Sandstone Patio — Conwy",
  },
  {
    id: "indian-sandstone-patio-conwy-03",
    src: "/images/projects/indian-sandstone-patio-conwy/indian-sandstone-patio-conwy-progress-03.jpg",
    alt: "Indian sandstone patio with circular feature by Cimatti & Roberts in Conwy, North Wales — progress view",
    category: "paving",
    projectSlug: "indian-sandstone-patio-conwy",
    projectTitle: "Indian Sandstone Patio — Conwy",
  },
  {
    id: "indian-sandstone-patio-conwy-04",
    src: "/images/projects/indian-sandstone-patio-conwy/indian-sandstone-patio-conwy-exterior-04.jpg",
    alt: "Indian sandstone patio with circular feature by Cimatti & Roberts in Conwy, North Wales — exterior view",
    category: "paving",
    projectSlug: "indian-sandstone-patio-conwy",
    projectTitle: "Indian Sandstone Patio — Conwy",
  },
  {
    id: "indian-sandstone-patio-conwy-05",
    src: "/images/projects/indian-sandstone-patio-conwy/indian-sandstone-patio-conwy-interior-05.jpg",
    alt: "Indian sandstone patio with circular feature by Cimatti & Roberts in Conwy, North Wales — interior view",
    category: "paving",
    projectSlug: "indian-sandstone-patio-conwy",
    projectTitle: "Indian Sandstone Patio — Conwy",
  },
  {
    id: "indian-sandstone-patio-conwy-06",
    src: "/images/projects/indian-sandstone-patio-conwy/indian-sandstone-patio-conwy-foundation-06.jpg",
    alt: "Indian sandstone patio with circular feature by Cimatti & Roberts in Conwy, North Wales — foundation view",
    category: "paving",
    projectSlug: "indian-sandstone-patio-conwy",
    projectTitle: "Indian Sandstone Patio — Conwy",
  },
  {
    id: "garden-transformation-conwy-02",
    src: "/images/projects/garden-transformation-conwy/garden-transformation-conwy-detail-02.jpg",
    alt: "Back garden before patio transformation by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "paving",
    projectSlug: "garden-transformation-conwy",
    projectTitle: "Garden Transformation — Conwy",
  },
  {
    id: "garden-transformation-conwy-03",
    src: "/images/projects/garden-transformation-conwy/garden-transformation-conwy-progress-03.jpg",
    alt: "Back garden before patio transformation by Cimatti & Roberts in Conwy, North Wales — progress view",
    category: "paving",
    projectSlug: "garden-transformation-conwy",
    projectTitle: "Garden Transformation — Conwy",
  },
  {
    id: "garden-transformation-conwy-04",
    src: "/images/projects/garden-transformation-conwy/garden-transformation-conwy-exterior-04.jpg",
    alt: "Back garden before patio transformation by Cimatti & Roberts in Conwy, North Wales — exterior view",
    category: "paving",
    projectSlug: "garden-transformation-conwy",
    projectTitle: "Garden Transformation — Conwy",
  },
  {
    id: "garden-transformation-conwy-05",
    src: "/images/projects/garden-transformation-conwy/garden-transformation-conwy-interior-05.jpg",
    alt: "Back garden before patio transformation by Cimatti & Roberts in Conwy, North Wales — interior view",
    category: "paving",
    projectSlug: "garden-transformation-conwy",
    projectTitle: "Garden Transformation — Conwy",
  },
  {
    id: "garden-transformation-conwy-06",
    src: "/images/projects/garden-transformation-conwy/garden-transformation-conwy-foundation-06.jpg",
    alt: "Back garden before patio transformation by Cimatti & Roberts in Conwy, North Wales — foundation view",
    category: "paving",
    projectSlug: "garden-transformation-conwy",
    projectTitle: "Garden Transformation — Conwy",
  },
  {
    id: "garden-transformation-conwy-07",
    src: "/images/projects/garden-transformation-conwy/garden-transformation-conwy-blockwork-07.jpg",
    alt: "Back garden before patio transformation by Cimatti & Roberts in Conwy, North Wales — blockwork view",
    category: "paving",
    projectSlug: "garden-transformation-conwy",
    projectTitle: "Garden Transformation — Conwy",
  },
  {
    id: "garden-transformation-conwy-08",
    src: "/images/projects/garden-transformation-conwy/garden-transformation-conwy-completed-08.jpg",
    alt: "Back garden before patio transformation by Cimatti & Roberts in Conwy, North Wales — completed view",
    category: "paving",
    projectSlug: "garden-transformation-conwy",
    projectTitle: "Garden Transformation — Conwy",
  },
  {
    id: "garden-transformation-conwy-09",
    src: "/images/projects/garden-transformation-conwy/garden-transformation-conwy-finishing-09.jpg",
    alt: "Back garden before patio transformation by Cimatti & Roberts in Conwy, North Wales — finishing view",
    category: "paving",
    projectSlug: "garden-transformation-conwy",
    projectTitle: "Garden Transformation — Conwy",
  },
  {
    id: "garden-transformation-conwy-10",
    src: "/images/projects/garden-transformation-conwy/garden-transformation-conwy-overview-10.jpg",
    alt: "Back garden before patio transformation by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "paving",
    projectSlug: "garden-transformation-conwy",
    projectTitle: "Garden Transformation — Conwy",
  },
  {
    id: "garden-transformation-conwy-11",
    src: "/images/projects/garden-transformation-conwy/garden-transformation-conwy-detail-11.jpg",
    alt: "Back garden before patio transformation by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "paving",
    projectSlug: "garden-transformation-conwy",
    projectTitle: "Garden Transformation — Conwy",
  },
  {
    id: "garden-transformation-conwy-12",
    src: "/images/projects/garden-transformation-conwy/garden-transformation-conwy-progress-12.jpg",
    alt: "Back garden before patio transformation by Cimatti & Roberts in Conwy, North Wales — progress view",
    category: "paving",
    projectSlug: "garden-transformation-conwy",
    projectTitle: "Garden Transformation — Conwy",
  },
  {
    id: "garden-transformation-conwy-13",
    src: "/images/projects/garden-transformation-conwy/garden-transformation-conwy-exterior-13.jpg",
    alt: "Back garden before patio transformation by Cimatti & Roberts in Conwy, North Wales — exterior view",
    category: "paving",
    projectSlug: "garden-transformation-conwy",
    projectTitle: "Garden Transformation — Conwy",
  },
  {
    id: "garden-transformation-conwy-14",
    src: "/images/projects/garden-transformation-conwy/garden-transformation-conwy-interior-14.jpg",
    alt: "Back garden before patio transformation by Cimatti & Roberts in Conwy, North Wales — interior view",
    category: "paving",
    projectSlug: "garden-transformation-conwy",
    projectTitle: "Garden Transformation — Conwy",
  },
  {
    id: "garden-transformation-conwy-15",
    src: "/images/projects/garden-transformation-conwy/garden-transformation-conwy-foundation-15.jpg",
    alt: "Back garden before patio transformation by Cimatti & Roberts in Conwy, North Wales — foundation view",
    category: "paving",
    projectSlug: "garden-transformation-conwy",
    projectTitle: "Garden Transformation — Conwy",
  },
  {
    id: "garden-transformation-conwy-16",
    src: "/images/projects/garden-transformation-conwy/garden-transformation-conwy-blockwork-16.jpg",
    alt: "Back garden before patio transformation by Cimatti & Roberts in Conwy, North Wales — blockwork view",
    category: "paving",
    projectSlug: "garden-transformation-conwy",
    projectTitle: "Garden Transformation — Conwy",
  },
  {
    id: "garden-transformation-conwy-17",
    src: "/images/projects/garden-transformation-conwy/garden-transformation-conwy-completed-17.jpg",
    alt: "Back garden before patio transformation by Cimatti & Roberts in Conwy, North Wales — completed view",
    category: "paving",
    projectSlug: "garden-transformation-conwy",
    projectTitle: "Garden Transformation — Conwy",
  },
  {
    id: "window-lintel-installation-conwy-01",
    src: "/images/projects/window-lintel-installation-conwy/window-lintel-installation-conwy-overview-01.jpg",
    alt: "Structural concrete lintel and window opening by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "structural",
    projectSlug: "window-lintel-installation-conwy",
    projectTitle: "Window Lintel Installation — Conwy",
  },
  {
    id: "window-lintel-installation-conwy-02",
    src: "/images/projects/window-lintel-installation-conwy/window-lintel-installation-conwy-detail-02.jpg",
    alt: "Structural concrete lintel and window opening by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "structural",
    projectSlug: "window-lintel-installation-conwy",
    projectTitle: "Window Lintel Installation — Conwy",
  },
  {
    id: "window-lintel-installation-conwy-03",
    src: "/images/projects/window-lintel-installation-conwy/window-lintel-installation-conwy-progress-03.jpg",
    alt: "Structural concrete lintel and window opening by Cimatti & Roberts in Conwy, North Wales — progress view",
    category: "structural",
    projectSlug: "window-lintel-installation-conwy",
    projectTitle: "Window Lintel Installation — Conwy",
  },
  {
    id: "window-lintel-installation-conwy-04",
    src: "/images/projects/window-lintel-installation-conwy/window-lintel-installation-conwy-exterior-04.jpg",
    alt: "Structural concrete lintel and window opening by Cimatti & Roberts in Conwy, North Wales — exterior view",
    category: "structural",
    projectSlug: "window-lintel-installation-conwy",
    projectTitle: "Window Lintel Installation — Conwy",
  },
  {
    id: "window-lintel-installation-conwy-05",
    src: "/images/projects/window-lintel-installation-conwy/window-lintel-installation-conwy-interior-05.jpg",
    alt: "Structural concrete lintel and window opening by Cimatti & Roberts in Conwy, North Wales — interior view",
    category: "structural",
    projectSlug: "window-lintel-installation-conwy",
    projectTitle: "Window Lintel Installation — Conwy",
  },
  {
    id: "corner-sandstone-patio-conwy-01",
    src: "/images/projects/corner-sandstone-patio-conwy/corner-sandstone-patio-conwy-overview-01.jpg",
    alt: "Natural stone patio in a walled garden corner by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "paving",
    projectSlug: "corner-sandstone-patio-conwy",
    projectTitle: "Corner Sandstone Patio — Conwy",
  },
  {
    id: "corner-sandstone-patio-conwy-02",
    src: "/images/projects/corner-sandstone-patio-conwy/corner-sandstone-patio-conwy-detail-02.jpg",
    alt: "Natural stone patio in a walled garden corner by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "paving",
    projectSlug: "corner-sandstone-patio-conwy",
    projectTitle: "Corner Sandstone Patio — Conwy",
  },
  {
    id: "stepped-brick-boundary-wall-conwy-01",
    src: "/images/projects/stepped-brick-boundary-wall-conwy/stepped-brick-boundary-wall-conwy-overview-01.jpg",
    alt: "Stepped red brick boundary wall by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "bricklaying",
    projectSlug: "stepped-brick-boundary-wall-conwy",
    projectTitle: "Stepped Brick Boundary Wall — Conwy",
  },
  {
    id: "stepped-brick-boundary-wall-conwy-02",
    src: "/images/projects/stepped-brick-boundary-wall-conwy/stepped-brick-boundary-wall-conwy-detail-02.jpg",
    alt: "Stepped red brick boundary wall by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "bricklaying",
    projectSlug: "stepped-brick-boundary-wall-conwy",
    projectTitle: "Stepped Brick Boundary Wall — Conwy",
  },
  {
    id: "stepped-brick-boundary-wall-conwy-03",
    src: "/images/projects/stepped-brick-boundary-wall-conwy/stepped-brick-boundary-wall-conwy-progress-03.jpg",
    alt: "Stepped red brick boundary wall by Cimatti & Roberts in Conwy, North Wales — progress view",
    category: "bricklaying",
    projectSlug: "stepped-brick-boundary-wall-conwy",
    projectTitle: "Stepped Brick Boundary Wall — Conwy",
  },
  {
    id: "stepped-brick-boundary-wall-conwy-04",
    src: "/images/projects/stepped-brick-boundary-wall-conwy/stepped-brick-boundary-wall-conwy-exterior-04.jpg",
    alt: "Stepped red brick boundary wall by Cimatti & Roberts in Conwy, North Wales — exterior view",
    category: "bricklaying",
    projectSlug: "stepped-brick-boundary-wall-conwy",
    projectTitle: "Stepped Brick Boundary Wall — Conwy",
  },
  {
    id: "stepped-brick-boundary-wall-conwy-05",
    src: "/images/projects/stepped-brick-boundary-wall-conwy/stepped-brick-boundary-wall-conwy-interior-05.jpg",
    alt: "Stepped red brick boundary wall by Cimatti & Roberts in Conwy, North Wales — interior view",
    category: "bricklaying",
    projectSlug: "stepped-brick-boundary-wall-conwy",
    projectTitle: "Stepped Brick Boundary Wall — Conwy",
  },
  {
    id: "stepped-brick-boundary-wall-conwy-06",
    src: "/images/projects/stepped-brick-boundary-wall-conwy/stepped-brick-boundary-wall-conwy-foundation-06.jpg",
    alt: "Stepped red brick boundary wall by Cimatti & Roberts in Conwy, North Wales — foundation view",
    category: "bricklaying",
    projectSlug: "stepped-brick-boundary-wall-conwy",
    projectTitle: "Stepped Brick Boundary Wall — Conwy",
  },
  {
    id: "stepped-brick-boundary-wall-conwy-07",
    src: "/images/projects/stepped-brick-boundary-wall-conwy/stepped-brick-boundary-wall-conwy-blockwork-07.jpg",
    alt: "Stepped red brick boundary wall by Cimatti & Roberts in Conwy, North Wales — blockwork view",
    category: "bricklaying",
    projectSlug: "stepped-brick-boundary-wall-conwy",
    projectTitle: "Stepped Brick Boundary Wall — Conwy",
  },
  {
    id: "rear-home-extension-conwy-02",
    src: "/images/projects/rear-home-extension-conwy/rear-home-extension-conwy-detail-02.jpg",
    alt: "Rear brick home extension progress by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "extensions",
    projectSlug: "rear-home-extension-conwy",
    projectTitle: "Rear Home Extension — Conwy",
  },
  {
    id: "rear-home-extension-conwy-03",
    src: "/images/projects/rear-home-extension-conwy/rear-home-extension-conwy-progress-03.jpg",
    alt: "Rear brick home extension progress by Cimatti & Roberts in Conwy, North Wales — progress view",
    category: "extensions",
    projectSlug: "rear-home-extension-conwy",
    projectTitle: "Rear Home Extension — Conwy",
  },
  {
    id: "rear-home-extension-conwy-04",
    src: "/images/projects/rear-home-extension-conwy/rear-home-extension-conwy-exterior-04.jpg",
    alt: "Rear brick home extension progress by Cimatti & Roberts in Conwy, North Wales — exterior view",
    category: "extensions",
    projectSlug: "rear-home-extension-conwy",
    projectTitle: "Rear Home Extension — Conwy",
  },
  {
    id: "rear-home-extension-conwy-05",
    src: "/images/projects/rear-home-extension-conwy/rear-home-extension-conwy-interior-05.jpg",
    alt: "Rear brick home extension progress by Cimatti & Roberts in Conwy, North Wales — interior view",
    category: "extensions",
    projectSlug: "rear-home-extension-conwy",
    projectTitle: "Rear Home Extension — Conwy",
  },
  {
    id: "raised-block-planter-conwy-01",
    src: "/images/projects/raised-block-planter-conwy/raised-block-planter-conwy-overview-01.jpg",
    alt: "Raised concrete block planter by Cimatti & Roberts in a Conwy garden — overview view",
    category: "bricklaying",
    projectSlug: "raised-block-planter-conwy",
    projectTitle: "Raised Block Planter — Conwy",
  },
  {
    id: "raised-block-planter-conwy-02",
    src: "/images/projects/raised-block-planter-conwy/raised-block-planter-conwy-detail-02.jpg",
    alt: "Raised concrete block planter by Cimatti & Roberts in a Conwy garden — detail view",
    category: "bricklaying",
    projectSlug: "raised-block-planter-conwy",
    projectTitle: "Raised Block Planter — Conwy",
  },
  {
    id: "raised-block-planter-conwy-03",
    src: "/images/projects/raised-block-planter-conwy/raised-block-planter-conwy-progress-03.jpg",
    alt: "Raised concrete block planter by Cimatti & Roberts in a Conwy garden — progress view",
    category: "bricklaying",
    projectSlug: "raised-block-planter-conwy",
    projectTitle: "Raised Block Planter — Conwy",
  },
  {
    id: "raised-block-planter-conwy-04",
    src: "/images/projects/raised-block-planter-conwy/raised-block-planter-conwy-exterior-04.jpg",
    alt: "Raised concrete block planter by Cimatti & Roberts in a Conwy garden — exterior view",
    category: "bricklaying",
    projectSlug: "raised-block-planter-conwy",
    projectTitle: "Raised Block Planter — Conwy",
  },
  {
    id: "raised-block-planter-conwy-05",
    src: "/images/projects/raised-block-planter-conwy/raised-block-planter-conwy-interior-05.jpg",
    alt: "Raised concrete block planter by Cimatti & Roberts in a Conwy garden — interior view",
    category: "bricklaying",
    projectSlug: "raised-block-planter-conwy",
    projectTitle: "Raised Block Planter — Conwy",
  },
  {
    id: "modern-patio-conwy-01",
    src: "/images/projects/modern-patio-conwy/modern-patio-conwy-overview-01.jpg",
    alt: "Light grey porcelain patio by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "paving",
    projectSlug: "modern-patio-conwy",
    projectTitle: "Modern Patio Installation — Conwy",
  },
  {
    id: "modern-patio-conwy-02",
    src: "/images/projects/modern-patio-conwy/modern-patio-conwy-detail-02.jpg",
    alt: "Light grey porcelain patio by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "paving",
    projectSlug: "modern-patio-conwy",
    projectTitle: "Modern Patio Installation — Conwy",
  },
  {
    id: "modern-patio-conwy-03",
    src: "/images/projects/modern-patio-conwy/modern-patio-conwy-progress-03.jpg",
    alt: "Light grey porcelain patio by Cimatti & Roberts in Conwy, North Wales — progress view",
    category: "paving",
    projectSlug: "modern-patio-conwy",
    projectTitle: "Modern Patio Installation — Conwy",
  },
  {
    id: "timber-fence-concrete-posts-conwy-01",
    src: "/images/projects/timber-fence-concrete-posts-conwy/timber-fence-concrete-posts-conwy-overview-01.jpg",
    alt: "Timber fence with concrete posts by Cimatti & Roberts in Conwy — overview view",
    category: "structural",
    projectSlug: "timber-fence-concrete-posts-conwy",
    projectTitle: "Timber Fence with Concrete Posts — Conwy",
  },
  {
    id: "modern-patio-conwy-04",
    src: "/images/projects/modern-patio-conwy/modern-patio-conwy-exterior-04.jpg",
    alt: "Light grey porcelain patio by Cimatti & Roberts in Conwy, North Wales — exterior view",
    category: "paving",
    projectSlug: "modern-patio-conwy",
    projectTitle: "Modern Patio Installation — Conwy",
  },
  {
    id: "modern-patio-conwy-05",
    src: "/images/projects/modern-patio-conwy/modern-patio-conwy-interior-05.jpg",
    alt: "Completed light grey patio by Cimatti & Roberts in Conwy, North Wales — interior view",
    category: "paving",
    projectSlug: "modern-patio-conwy",
    projectTitle: "Modern Patio Installation — Conwy",
  },
  {
    id: "modern-patio-conwy-06",
    src: "/images/projects/modern-patio-conwy/modern-patio-conwy-foundation-06.jpg",
    alt: "Completed light grey patio by Cimatti & Roberts in Conwy, North Wales — foundation view",
    category: "paving",
    projectSlug: "modern-patio-conwy",
    projectTitle: "Modern Patio Installation — Conwy",
  },
  {
    id: "porch-extension-foundation-conwy-01",
    src: "/images/projects/porch-extension-foundation-conwy/porch-extension-foundation-conwy-overview-01.jpg",
    alt: "Brick and block porch extension foundation by Cimatti & Roberts in Conwy — overview view",
    category: "extensions",
    projectSlug: "porch-extension-foundation-conwy",
    projectTitle: "Porch Extension Foundation — Conwy",
  },
  {
    id: "porch-extension-foundation-conwy-02",
    src: "/images/projects/porch-extension-foundation-conwy/porch-extension-foundation-conwy-detail-02.jpg",
    alt: "Brick and block porch extension foundation by Cimatti & Roberts in Conwy — detail view",
    category: "extensions",
    projectSlug: "porch-extension-foundation-conwy",
    projectTitle: "Porch Extension Foundation — Conwy",
  },
  {
    id: "porch-extension-foundation-conwy-03",
    src: "/images/projects/porch-extension-foundation-conwy/porch-extension-foundation-conwy-progress-03.jpg",
    alt: "Brick and block porch extension foundation by Cimatti & Roberts in Conwy — progress view",
    category: "extensions",
    projectSlug: "porch-extension-foundation-conwy",
    projectTitle: "Porch Extension Foundation — Conwy",
  },
  {
    id: "porch-extension-foundation-conwy-04",
    src: "/images/projects/porch-extension-foundation-conwy/porch-extension-foundation-conwy-exterior-04.jpg",
    alt: "Brick and block porch extension foundation by Cimatti & Roberts in Conwy — exterior view",
    category: "extensions",
    projectSlug: "porch-extension-foundation-conwy",
    projectTitle: "Porch Extension Foundation — Conwy",
  },
  {
    id: "porch-extension-foundation-conwy-05",
    src: "/images/projects/porch-extension-foundation-conwy/porch-extension-foundation-conwy-interior-05.jpg",
    alt: "Brick and block porch extension foundation by Cimatti & Roberts in Conwy — interior view",
    category: "extensions",
    projectSlug: "porch-extension-foundation-conwy",
    projectTitle: "Porch Extension Foundation — Conwy",
  },
  {
    id: "porch-extension-foundation-conwy-06",
    src: "/images/projects/porch-extension-foundation-conwy/porch-extension-foundation-conwy-foundation-06.jpg",
    alt: "Brick and block porch extension foundation by Cimatti & Roberts in Conwy — foundation view",
    category: "extensions",
    projectSlug: "porch-extension-foundation-conwy",
    projectTitle: "Porch Extension Foundation — Conwy",
  },
  {
    id: "porch-extension-foundation-conwy-07",
    src: "/images/projects/porch-extension-foundation-conwy/porch-extension-foundation-conwy-blockwork-07.jpg",
    alt: "Brick and block porch extension foundation by Cimatti & Roberts in Conwy — blockwork view",
    category: "extensions",
    projectSlug: "porch-extension-foundation-conwy",
    projectTitle: "Porch Extension Foundation — Conwy",
  },
  {
    id: "porch-extension-foundation-conwy-08",
    src: "/images/projects/porch-extension-foundation-conwy/porch-extension-foundation-conwy-completed-08.jpg",
    alt: "Brick and block porch extension foundation by Cimatti & Roberts in Conwy — completed view",
    category: "extensions",
    projectSlug: "porch-extension-foundation-conwy",
    projectTitle: "Porch Extension Foundation — Conwy",
  },
  {
    id: "patio-raised-planter-conwy-01",
    src: "/images/projects/patio-raised-planter-conwy/patio-raised-planter-conwy-overview-01.jpg",
    alt: "Patio paving and raised planter by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "paving",
    projectSlug: "patio-raised-planter-conwy",
    projectTitle: "Patio & Raised Planter — Conwy",
  },
  {
    id: "patio-raised-planter-conwy-02",
    src: "/images/projects/patio-raised-planter-conwy/patio-raised-planter-conwy-detail-02.jpg",
    alt: "Patio paving and raised planter by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "paving",
    projectSlug: "patio-raised-planter-conwy",
    projectTitle: "Patio & Raised Planter — Conwy",
  },
  {
    id: "patio-raised-planter-conwy-03",
    src: "/images/projects/patio-raised-planter-conwy/patio-raised-planter-conwy-progress-03.jpg",
    alt: "Patio paving and raised planter by Cimatti & Roberts in Conwy, North Wales — progress view",
    category: "paving",
    projectSlug: "patio-raised-planter-conwy",
    projectTitle: "Patio & Raised Planter — Conwy",
  },
  {
    id: "patio-raised-planter-conwy-04",
    src: "/images/projects/patio-raised-planter-conwy/patio-raised-planter-conwy-exterior-04.jpg",
    alt: "Patio paving and raised planter by Cimatti & Roberts in Conwy, North Wales — exterior view",
    category: "paving",
    projectSlug: "patio-raised-planter-conwy",
    projectTitle: "Patio & Raised Planter — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-01",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-overview-01.jpg",
    alt: "Interior renovation and plastering by Cimatti & Roberts in Conwy — overview view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-02",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-detail-02.jpg",
    alt: "Interior renovation and plastering by Cimatti & Roberts in Conwy — detail view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-03",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-progress-03.jpg",
    alt: "Structural wall removal for open-plan kitchen by Cimatti & Roberts in Conwy, North Wales — progress view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-04",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-exterior-04.jpg",
    alt: "Structural wall removal for open-plan kitchen by Cimatti & Roberts in Conwy, North Wales — exterior view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-05",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-interior-05.jpg",
    alt: "Structural wall removal for open-plan kitchen by Cimatti & Roberts in Conwy, North Wales — interior view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-06",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-foundation-06.jpg",
    alt: "Structural wall removal for open-plan kitchen by Cimatti & Roberts in Conwy, North Wales — foundation view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-07",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-blockwork-07.jpg",
    alt: "Interior renovation and plastering by Cimatti & Roberts in Conwy — blockwork view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-08",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-completed-08.jpg",
    alt: "Structural wall removal for open-plan kitchen by Cimatti & Roberts in Conwy, North Wales — completed view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "home-extension-pebbledash-conwy-01",
    src: "/images/projects/home-extension-pebbledash-conwy/home-extension-pebbledash-conwy-overview-01.jpg",
    alt: "Single-storey home extension with red brick base by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "extensions",
    projectSlug: "home-extension-pebbledash-conwy",
    projectTitle: "Home Extension — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-09",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-finishing-09.jpg",
    alt: "Interior renovation and plastering by Cimatti & Roberts in Conwy — finishing view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "home-extension-pebbledash-conwy-02",
    src: "/images/projects/home-extension-pebbledash-conwy/home-extension-pebbledash-conwy-detail-02.jpg",
    alt: "Rear home extension with steel lintel by Cimatti & Roberts in Conwy — detail view",
    category: "extensions",
    projectSlug: "home-extension-pebbledash-conwy",
    projectTitle: "Home Extension — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-10",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-overview-10.jpg",
    alt: "Structural wall removal for open-plan kitchen by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-11",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-detail-11.jpg",
    alt: "Structural wall removal for open-plan kitchen by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-12",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-progress-12.jpg",
    alt: "Structural wall removal for open-plan kitchen by Cimatti & Roberts in Conwy, North Wales — progress view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-13",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-exterior-13.jpg",
    alt: "Structural wall removal for open-plan kitchen by Cimatti & Roberts in Conwy, North Wales — exterior view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-14",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-interior-14.jpg",
    alt: "Structural wall removal for open-plan kitchen by Cimatti & Roberts in Conwy, North Wales — interior view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-15",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-foundation-15.jpg",
    alt: "Structural wall removal for open-plan kitchen by Cimatti & Roberts in Conwy, North Wales — foundation view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-16",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-blockwork-16.jpg",
    alt: "Interior renovation and plastering by Cimatti & Roberts in Conwy — blockwork view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-17",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-completed-17.jpg",
    alt: "Structural wall removal for open-plan kitchen by Cimatti & Roberts in Conwy, North Wales — completed view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-18",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-finishing-18.jpg",
    alt: "Interior renovation and plastering by Cimatti & Roberts in Conwy — finishing view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-19",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-overview-19.jpg",
    alt: "Interior renovation and plastering by Cimatti & Roberts in Conwy — overview view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-20",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-detail-20.jpg",
    alt: "Interior renovation and plastering by Cimatti & Roberts in Conwy — detail view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "home-extension-pebbledash-conwy-03",
    src: "/images/projects/home-extension-pebbledash-conwy/home-extension-pebbledash-conwy-progress-03.jpg",
    alt: "Concrete blockwork home extension by Cimatti & Roberts in Conwy, North Wales — progress view",
    category: "extensions",
    projectSlug: "home-extension-pebbledash-conwy",
    projectTitle: "Home Extension — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-21",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-progress-21.jpg",
    alt: "Structural wall removal for open-plan kitchen by Cimatti & Roberts in Conwy, North Wales — progress view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "home-extension-pebbledash-conwy-04",
    src: "/images/projects/home-extension-pebbledash-conwy/home-extension-pebbledash-conwy-exterior-04.jpg",
    alt: "Home extension blockwork with structural lintel by Cimatti & Roberts in Conwy, North Wales — exterior view",
    category: "extensions",
    projectSlug: "home-extension-pebbledash-conwy",
    projectTitle: "Home Extension — Conwy",
  },
  {
    id: "open-plan-kitchen-renovation-conwy-22",
    src: "/images/projects/open-plan-kitchen-renovation-conwy/open-plan-kitchen-renovation-conwy-exterior-22.jpg",
    alt: "Structural wall removal for open-plan kitchen by Cimatti & Roberts in Conwy, North Wales — exterior view",
    category: "structural",
    projectSlug: "open-plan-kitchen-renovation-conwy",
    projectTitle: "Open-Plan Kitchen Renovation — Conwy",
  },
  {
    id: "brick-garage-construction-conwy-01",
    src: "/images/projects/brick-garage-construction-conwy/brick-garage-construction-conwy-overview-01.jpg",
    alt: "New brick and block garage by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "extensions",
    projectSlug: "brick-garage-construction-conwy",
    projectTitle: "Brick Garage Construction — Conwy",
  },
  {
    id: "brick-garage-construction-conwy-02",
    src: "/images/projects/brick-garage-construction-conwy/brick-garage-construction-conwy-detail-02.jpg",
    alt: "New brick and block garage by Cimatti & Roberts in Conwy, North Wales — detail view",
    category: "extensions",
    projectSlug: "brick-garage-construction-conwy",
    projectTitle: "Brick Garage Construction — Conwy",
  },
  {
    id: "brick-garage-construction-conwy-03",
    src: "/images/projects/brick-garage-construction-conwy/brick-garage-construction-conwy-progress-03.jpg",
    alt: "Red brick outbuilding construction by Cimatti & Roberts in Conwy — progress view",
    category: "extensions",
    projectSlug: "brick-garage-construction-conwy",
    projectTitle: "Brick Garage Construction — Conwy",
  },
  {
    id: "brick-garage-construction-conwy-04",
    src: "/images/projects/brick-garage-construction-conwy/brick-garage-construction-conwy-exterior-04.jpg",
    alt: "New brick and block garage by Cimatti & Roberts in Conwy, North Wales — exterior view",
    category: "extensions",
    projectSlug: "brick-garage-construction-conwy",
    projectTitle: "Brick Garage Construction — Conwy",
  },
  {
    id: "brick-garage-construction-conwy-05",
    src: "/images/projects/brick-garage-construction-conwy/brick-garage-construction-conwy-interior-05.jpg",
    alt: "New brick and block garage by Cimatti & Roberts in Conwy, North Wales — interior view",
    category: "extensions",
    projectSlug: "brick-garage-construction-conwy",
    projectTitle: "Brick Garage Construction — Conwy",
  },
  {
    id: "brick-garage-construction-conwy-06",
    src: "/images/projects/brick-garage-construction-conwy/brick-garage-construction-conwy-foundation-06.jpg",
    alt: "New brick and block garage by Cimatti & Roberts in Conwy, North Wales — foundation view",
    category: "extensions",
    projectSlug: "brick-garage-construction-conwy",
    projectTitle: "Brick Garage Construction — Conwy",
  },
  {
    id: "brick-garage-construction-conwy-07",
    src: "/images/projects/brick-garage-construction-conwy/brick-garage-construction-conwy-blockwork-07.jpg",
    alt: "Red brick outbuilding construction by Cimatti & Roberts in Conwy — blockwork view",
    category: "extensions",
    projectSlug: "brick-garage-construction-conwy",
    projectTitle: "Brick Garage Construction — Conwy",
  },
  {
    id: "brick-garage-construction-conwy-08",
    src: "/images/projects/brick-garage-construction-conwy/brick-garage-construction-conwy-completed-08.jpg",
    alt: "Red brick outbuilding construction by Cimatti & Roberts in Conwy — completed view",
    category: "extensions",
    projectSlug: "brick-garage-construction-conwy",
    projectTitle: "Brick Garage Construction — Conwy",
  },
  {
    id: "brick-garage-construction-conwy-09",
    src: "/images/projects/brick-garage-construction-conwy/brick-garage-construction-conwy-finishing-09.jpg",
    alt: "Red brick outbuilding construction by Cimatti & Roberts in Conwy — finishing view",
    category: "extensions",
    projectSlug: "brick-garage-construction-conwy",
    projectTitle: "Brick Garage Construction — Conwy",
  },
  {
    id: "brick-garage-construction-conwy-10",
    src: "/images/projects/brick-garage-construction-conwy/brick-garage-construction-conwy-overview-10.jpg",
    alt: "New brick and block garage by Cimatti & Roberts in Conwy, North Wales — overview view",
    category: "extensions",
    projectSlug: "brick-garage-construction-conwy",
    projectTitle: "Brick Garage Construction — Conwy",
  },
  {
    id: "brick-garage-construction-conwy-11",
    src: "/images/projects/brick-garage-construction-conwy/brick-garage-construction-conwy-detail-11.jpg",
    alt: "Red brick outbuilding construction by Cimatti & Roberts in Conwy — detail view",
    category: "extensions",
    projectSlug: "brick-garage-construction-conwy",
    projectTitle: "Brick Garage Construction — Conwy",
  },
  {
    id: "brick-garage-construction-conwy-12",
    src: "/images/projects/brick-garage-construction-conwy/brick-garage-construction-conwy-progress-12.jpg",
    alt: "Red brick outbuilding construction by Cimatti & Roberts in Conwy — progress view",
    category: "extensions",
    projectSlug: "brick-garage-construction-conwy",
    projectTitle: "Brick Garage Construction — Conwy",
  },
  {
    id: "brick-garage-construction-conwy-13",
    src: "/images/projects/brick-garage-construction-conwy/brick-garage-construction-conwy-exterior-13.jpg",
    alt: "New brick and block garage by Cimatti & Roberts in Conwy, North Wales — exterior view",
    category: "extensions",
    projectSlug: "brick-garage-construction-conwy",
    projectTitle: "Brick Garage Construction — Conwy",
  },
  {
    id: "brick-garage-construction-conwy-14",
    src: "/images/projects/brick-garage-construction-conwy/brick-garage-construction-conwy-interior-14.jpg",
    alt: "New brick and block garage by Cimatti & Roberts in Conwy, North Wales — interior view",
    category: "extensions",
    projectSlug: "brick-garage-construction-conwy",
    projectTitle: "Brick Garage Construction — Conwy",
  },
  {
    id: "brick-garage-construction-conwy-15",
    src: "/images/projects/brick-garage-construction-conwy/brick-garage-construction-conwy-foundation-15.jpg",
    alt: "New brick and block garage by Cimatti & Roberts in Conwy, North Wales — foundation view",
    category: "extensions",
    projectSlug: "brick-garage-construction-conwy",
    projectTitle: "Brick Garage Construction — Conwy",
  },
];
