type ServiceSlug =
  | "bricklaying"
  | "extensions"
  | "structural"
  | "repointing"
  | "general-building"
  | "groundwork"
  | "plastering"
  | "landscaping";

export const serviceDescriptions: Record<ServiceSlug, string[]> = {
  bricklaying: [
    "As bricklaying specialists with over 30 years of experience, Cimatti & Roberts delivers precise, durable brickwork for homeowners and commercial clients throughout Deganwy, Conwy, Llandudno and wider North Wales. Based at 57 Parc Pentywyn, Deganwy, our co-founders Sam Cimatti and Jason Roberts are hands-on on every project — from the first course to the final pointing.",
    "From garden walls and boundary work to new build brickwork and feature walls, we take pride in clean lines, level courses and a professional finish on every project. Our portfolio includes stepped boundary walls, decorative screen walls, garden walls with brick pillars, and cavity wall construction for extensions and new builds across Conwy and the surrounding coast.",
    "We work with a range of brick types and bond patterns to match existing property styles — whether you are extending a pebbledash home in Llandudno, building a new garage in Conwy, or adding a garden feature wall in Deganwy. Every job is planned carefully for weather, access and material delivery to keep disruption to a minimum.",
    "Bricklaying projects we regularly complete include single-skin and cavity garden walls, retaining walls, piers and gate posts, new build external leaf brickwork, and repair work to damaged or leaning walls. We also carry out brickwork as part of larger extension and new build packages.",
    "Cimatti & Roberts serves eight primary areas across North Wales: Deganwy, Conwy, Llandudno, Llandudno Junction, Colwyn Bay, Abergele, Rhyl and Bangor. If your property falls outside these towns, contact us — we cover wider North Wales and can usually accommodate your project.",
    "We are fully insured and quality is guaranteed on every job. All quotations are free and without obligation. Call Sam on 07872 463390 or Jason on 07861 140795, message us on WhatsApp, or use our online contact form to arrange a site visit and written quote.",
  ],
  extensions: [
    "Planning a home extension or new build in North Wales? Cimatti & Roberts brings more than 30 years of construction experience to every project, from single-storey kitchen extensions to full new build homes. We are a family-run company based in Deganwy, Conwy.",
    "We manage the build from groundwork and foundations through brickwork, structural alterations, plastering and completion — ensuring quality workmanship, clear communication and a tidy site throughout. Recent extension work includes rear home extensions, pebbledash extensions, brick garages and coastal block extensions across Conwy and the North Wales coast.",
    "Single-storey extensions are ideal for opening up kitchen and living spaces, adding ground-floor bedrooms, or creating utility and storage rooms. Double-storey extensions provide additional bedrooms and bathrooms upstairs while expanding living space below. We advise on practical layouts, structural requirements and how your extension will tie into existing brickwork and roof lines.",
    "For new build homes, we handle the full build envelope — footings, block and brickwork, structural openings, RSJ installation where required, and coordination with other trades. Sam and Jason remain your direct points of contact from the first site meeting through to handover.",
    "Our service area covers Deganwy, Conwy, Llandudno, Colwyn Bay, Abergele, Rhyl, Bangor and surrounding North Wales towns. We provide free advice and no-obligation written quotations on all extension and new build enquiries.",
    "Cimatti & Roberts is fully insured with quality guaranteed on every project. Contact Sam on 07872 463390 or Jason on 07861 140795 for a free consultation, or submit your details through our online contact form.",
    "We work to approved plans and building regulations requirements, coordinating inspections at foundation, structural and completion stages. If you are at the early planning stage, we can review your proposals and advise on buildability, timescales and realistic budgets before you commit.",
  ],
  structural: [
    "Structural alterations require experience, precision and the right equipment. Cimatti & Roberts provides professional wall openings, RSJ and steel beam installation, and structural work across North Wales. With over 30 years on site, co-founders Sam Cimatti and Jason Roberts understand load paths, temporary support and building regulations compliance.",
    "Whether you are removing a load-bearing wall to create an open-plan kitchen and living area, widening an opening for bi-fold doors, or installing steel beams for a loft conversion or extension, we ensure the work is completed safely and to a high standard. Our gallery includes open-plan kitchen renovations, window lintel installations and concrete base slabs across Conwy and Deganwy.",
    "Every structural project begins with a site assessment. We identify load-bearing elements, specify the correct steel section or lintel, and plan temporary works before any wall is removed. RSJ installations include pad stones, fire protection where required, and coordination with your building control inspector.",
    "Structural work often forms part of a wider renovation — combining wall removals with plastering, floor screeding and finishing trades. As a general building company, we can manage the full scope rather than leaving you to coordinate multiple contractors.",
    "We serve homeowners across Deganwy, Conwy, Llandudno, Llandudno Junction, Colwyn Bay, Abergele, Rhyl, Bangor and wider North Wales. Free advice and no-obligation quotations are available on all structural enquiries.",
    "Cimatti & Roberts is fully insured. Contact Sam on 07872 463390 or Jason on 07861 140795, or use our contact form to describe your project and arrange a site visit.",
    "Typical structural projects in North Wales include removing chimney breasts, creating through-lounge openings, supporting new loft floors, and installing steels for rear extension openings. We provide clear written quotations outlining the scope, materials and expected programme before work starts. Building control sign-off is arranged at the required stages.",
  ],
  repointing: [
    "Protect and restore your property with professional repointing and brick repair services from Cimatti & Roberts. We work on period properties and modern homes across North Wales — from stone chimney stacks on coastal properties to garden walls and gable ends in Conwy and Deganwy.",
    "Our repointing work includes traditional lime mortar where required for older buildings, cement-based repointing for modern brickwork, brick replacements for spalled or cracked units, and chimney repointing and repairs. Recent projects include stone chimney repointing across North Wales with documented before, during and after photography.",
    "Repointing is essential when mortar joints have eroded, allowing water ingress and frost damage to the brick faces. Early intervention prevents costlier rebuilds later. We rake out defective mortar to the correct depth, prepare joints and apply new mortar matched as closely as possible to the existing finish and colour.",
    "Heritage and period property owners in Conwy, Llandudno and surrounding areas trust us for careful, respectful repair work. We understand the difference between lime and cement mortars and advise on the correct approach for your building age and construction type.",
    "Cimatti & Roberts has more than 30 years of experience and is fully insured with quality guaranteed. We cover eight service areas across North Wales and offer free, no-obligation assessments and quotations.",
    "Contact co-founders Sam Cimatti (07872 463390) or Jason Roberts (07861 140795) to arrange a survey of your brickwork or chimney. WhatsApp and our online contact form are also available.",
    "Coastal properties in Deganwy, Conwy and Llandudno often need repointing sooner due to weather exposure. We assess the extent of mortar failure and brick damage before quoting, so you know exactly what work is required and why. Matching mortar colour and texture to existing joints is a priority on every repointing job. We also replace individual damaged bricks where units have cracked or spalled.",
  ],
  "general-building": [
    "Cimatti & Roberts offers a full range of general building and joinery services for homeowners and small commercial clients across North Wales. From property refurbishments and internal alterations to timber partitions and blockwork, we deliver reliable, professional results with the same attention to detail that defines all our projects.",
    "General building work covers the projects that do not fit a single trade — internal reconfigurations, stud wall partitions, blockwork walls, timber framing, making good after plumbing or electrical work, and small-scale refurbishments. Our gallery includes industrial blockwork walls, timber partition bedrooms and interior stud wall projects across Conwy.",
    "Joinery services include door hanging, architrave and skirting, timber framing for extensions, and bespoke carpentry as part of wider renovation packages. We work cleanly and tidily, protecting your home and clearing up at the end of each day — a standard praised in our Facebook reviews.",
    "As a company with 30+ years of experience, we are well placed to handle multi-stage refurbishments where bricklaying, plastering, structural work and finishing trades need to be coordinated. Sam and Jason manage each stage and keep you informed throughout.",
    "We serve Deganwy, Conwy, Llandudno, Colwyn Bay, Abergele, Rhyl, Bangor and surrounding North Wales areas. No job is too small or too large — from a single partition wall to a full property refurbishment.",
    "All quotations are free and without obligation. Cimatti & Roberts is fully insured. Call Sam on 07872 463390 or Jason on 07861 140795, or request a quote through our website contact form.",
    "Small commercial clients — including shops, offices and rental properties — use us for reliable repair work, alterations and refurbishments with minimal disruption to trading hours. We schedule work around your requirements wherever possible. All work is carried out by Sam, Jason and their trusted team — never sub-contracted without your knowledge.",
  ],
  groundwork: [
    "Solid foundations are essential for any construction project. Cimatti & Roberts provides professional footings, groundwork and drainage services across Deganwy, Conwy and North Wales. With over 30 years of site experience, we understand ground conditions, excavation safety and the building regulations requirements for foundations and drainage.",
    "Whether you need foundations for a home extension, a concrete base slab for a garage or outbuilding, blockwork foundations for a new wall, or drainage for a patio and landscaping project, we have the experience and equipment to get it done right. Our project gallery includes porch extension foundations, blockwork foundations and concrete base slabs across Conwy and North Wales.",
    "Groundwork typically includes setting out, excavation, compacted hardcore, concrete footings or slabs, damp proof membranes, and below-ground drainage connections. We coordinate with building control inspections at the correct stages and ensure trenches are safe and properly supported throughout.",
    "Land drainage solutions help prevent water pooling in gardens and against property walls — particularly important on sloped sites common across the Conwy and Deganwy area. We install land drains, soakaways and surface water channels as part of landscaping and extension projects.",
    "Cimatti & Roberts covers eight service areas across North Wales. We provide free advice and no-obligation quotations on all groundwork and drainage requirements, from small patio bases to full extension foundations.",
    "We are fully insured with quality guaranteed on every project. Contact Sam on 07872 463390 or Jason on 07861 140795 to discuss your site requirements and arrange a visit.",
    "Ground conditions in North Wales vary from rock close to the surface to softer ground near the coast. We assess each site individually and specify the correct foundation depth, reinforcement and drainage solution for your project. Excavated material is removed from site and work areas are left safe and tidy at the end of each day.",
  ],
  plastering: [
    "Complete your build or renovation with professional plastering and rendering from Cimatti & Roberts. We provide internal plastering and external rendering services across North Wales for new extensions, refurbishments and standalone repair projects.",
    "Internal plastering includes boarding and skimming new stud walls, replastering after structural alterations, patch repairs to damaged ceilings and walls, and full-room replastering as part of renovation packages. Our gallery shows interior plastering to stud walls, floor screeding and finished kitchen renovation spaces in Conwy.",
    "External rendering protects brick and blockwork from weather while giving a clean, uniform finish. We apply render systems to extension gables, full property re-renders, and repair areas of cracked or blown render. Pebbledash and textured finishes can be matched where required.",
    "Plastering and rendering is often the final stage before decoration — so a smooth, durable finish matters. We allow appropriate drying times, protect surrounding areas during application, and leave rooms ready for painting or tiling.",
    "Based in Deganwy, Conwy, Cimatti & Roberts serves Llandudno, Colwyn Bay, Abergele, Rhyl, Bangor and surrounding areas. With 30+ years of experience, we are a trusted choice for homeowners across the region.",
    "Free quotations are available on all plastering and rendering work. We are fully insured. Call Sam on 07872 463390 or Jason on 07861 140795, or submit an enquiry through our contact form.",
    "We frequently finish extension and structural projects with plastering and rendering, giving you a single team from foundations through to a decorated-ready surface. This reduces delays and keeps quality consistent across every stage of the build. Screeding, dot-and-dab boarding and skim coats are all completed to a paint-ready standard. Whether you need one room skimmed or a full extension plastered, we apply the same level of care throughout.",
  ],
  landscaping: [
    "Transform your outdoor space with professional paving, slabbing and landscaping from Cimatti & Roberts. We create beautiful, durable patios, driveways and garden areas across North Wales — from Indian sandstone patios with circular features to full garden transformations and modern porcelain patios in Conwy.",
    "Our landscaping and paving work includes excavation and groundwork, sub-base preparation, membrane and bedding sand, precision laying of slabs or block paving, edge restraints, pointing and finishing. We handle levels, falls for drainage, and integration with existing paths and door thresholds.",
    "Block paving is a popular choice for driveways and paths — hard-wearing and straightforward to repair if individual blocks are damaged later. Slab paving in Indian sandstone, porcelain or concrete offers a wide range of colours and sizes for patios and sitting areas.",
    "Full garden transformations may combine paving with wall building, steps, planting beds and turf. We work tidily and remove waste from site, leaving your garden ready to enjoy. Customer reviews on Facebook specifically praise our professionalism, cleanliness and precision on patio and landscaping projects.",
    "Cimatti & Roberts is based in Deganwy and serves Conwy, Llandudno, Colwyn Bay, Abergele, Rhyl, Bangor and wider North Wales. We have 30+ years of experience and offer free, no-obligation quotations.",
    "Contact Sam on 07872 463390 or Jason on 07861 140795, message us on WhatsApp, or use our online form to describe your paving or landscaping project and arrange a site visit.",
    "We advise on materials suited to North Wales weather — including frost-resistant paving, adequate falls for rainwater, and durable pointing that withstands coastal conditions. Every patio and driveway is built for long-term use, not just immediate appearance. View our gallery for examples of Indian sandstone, porcelain and block paving projects across Conwy. From small sitting areas to full garden makeovers, every outdoor project receives the same professional approach.",
  ],
};
